- name: Installing stow
  ansible.builtin.apt:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow
  become: true
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:{{ gh_username }}/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Remove .zshrc
  ansible.builtin.command:
    cmd: rm -f {{ lookup('env', 'HOME') }}/.zshrc
- name: Stow dotfiles
  ansible.builtin.shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
  changed_when: false
