- name: Install Yarn
  community.general.npm:
    name: yarn
    global: true
  tags:
    - install
    - node
- name: Install eslint
  community.general.npm:
    name: eslint
    global: true
  tags:
    - install
    - node
- name: Install Typescript server
  community.general.npm:
    name: typescript-language-server
    global: true
  tags:
    - install
    - node
- name: Install Typescript
  community.general.npm:
    name: typescript
    global: true
  tags:
    - install
    - node
- name: Install TS-Node
  community.general.npm:
    name: ts-node
    global: true
  tags:
    - install
    - node
