- name: Remove vscode
  community.general.snap:
    name: code
    state: absent
    classic: true
  become: true
  tags:
    - install
    - vscode
  when: 'not "microsoft" in ansible_facts["kernel"]'
- name: Install vscode
  community.general.snap:
    name: code
    classic: true
  become: true
  tags:
    - install
    - vscode
  when: 'not "microsoft" in ansible_facts["kernel"]'
- name: Install vscode extensions
  ansible.builtin.command: vscode/install-extensions.sh
  tags:
    - install
    - vscode
  register: installed
  changed_when: installed.rc != 0
